common:
  configuration: General

  
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA.SERVER.HOST:http://server-01.com:8761/eureka} 
      

#Enable Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: /actuator
# Enable zipkin traces
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    config:
      endpoint: http://localhost:9411/api/v2/spans

# Logging configuration
logging:
  level:
    org:
      springframework:
        web: ALL
    com:
      mitocode: ALL

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: false
    path: /openapi.yml    
              
        