# Kafka properties
kafka:
  mitocode:
    server: localhost
    topicName: mitocode
    topicName1: mitocode1
    port: 9092


# Mongo Configuration
spring:
  data:
    mongodb:
      uri: ${MONGODB.URL.CONNECTION:mongodb://mitocode:mitocode@localhost:27018/mitocode?authSource=admin}