server:
  port: ${CUSTOM.SERVER.PORT:9045}

# Postgres Configuration
spring:
  jpa:
    databasePlatform:
    hibernate: 
      ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource: 
    url: ${POSTGRESQL.URL.CONNECTION:jdbc:postgresql://localhost:5433/mitocode}
    username: mitocode
    password: '{cipher}bfbf1e901b797c054d5638bc4d71777c6397a6c3fc894f498e36012f617be99b'

kafka:
  mitocode:
    server: localhost
    topicName: mitocode
    topicName1: mitocode1
    port: 9092