server:
  port: ${CUSTOM.SERVER.PORT:9030}

# Mongo Configuration
spring:
  data:
    mongodb:
      uri: ${MONGODB.URL.CONNECTION:mongodb://magic0:mitocode@localhost:27017/mitocode?authSource=admin}

kafka:
  mitocode:
    server: ${KAFKA.SERVER.HOSTNAME:localhost}
    topicName: mitocode
    port: 9092